(ASDF/PARSE-DEFSYSTEM:DEFSYSTEM #:CL-WL.ZWLR-LAYER-SHELL
  :SERIAL
  T
  :LICENSE
  "GPLv3"
  :VERSION
  "0.0.1"
  :DEPENDS-ON
  (#:CFFI #:CL-ASYNC #:CL-WL #:CL-WL.FFI #:CL-WL.WAYLAND-CORE
   #:CL-WL.XDG-SHELL)
  :COMPONENTS
  ((:FILE "cl-wl.zwlr-layer-shell")))

